---
title: "EFA Analyses of the Measures"
output:
  html_document:
    theme: paper
    toc: true
  html_notebook: null
---

# Import the data 
```{r, import, message=FALSE, warning=FALSE}
# load packaes
if (!require("pacman")) install.packages("pacman")
pacman::p_load(MplusAutomation, psych, tidyr, foreign, ggplot2, ggalt, ggthemes, 
    readr, dplyr, knitr, scales, pander, lavaan, kableExtra, fa, GPArotation)
# Import the data ----
joined.dat <- readRDS(file = "../data/joined.dat")

# subset out the items
items <- joined.dat %>%
  select(s_preInt_Des_15, s_preInt_Des_17, s_preInt_Des_21, s_preInt_Des_24, s_preInt_Des_26, s_preInt_Des_29, 
         s_preInt_Des_33, s_preInt_Car_16, s_preInt_Car_18, s_preInt_Car_20, s_preInt_Car_23, s_preInt_Car_25, 
         s_preInt_Car_28, s_preInt_Car_30, s_preInt_Car_32, s_preInt_Car_34, s_preInt_Car_36, s_preInt_Self_19, 
         s_preInt_Self_22, s_preInt_Self_27, s_preInt_Self_31 ,s_preInt_Self_35)

rev.items.bifactor <- joined.dat %>%
  select(s_preInt_Car_30, s_preInt_Car_20, s_preInt_Car_16, s_preInt_Car_25, s_preInt_Car_36, s_preInt_Car_32, 
         s_preInt_Car_23, s_preInt_Car_18, s_preInt_Self_19, s_preInt_Self_22, s_preInt_Self_27, 
         s_preInt_Self_31,s_preInt_Self_35)

rev.items.secondOrder <- joined.dat %>%
  select(s_preInt_Car_30, s_preInt_Car_20, s_preInt_Car_16, s_preInt_Car_25, s_preInt_Car_34, s_preInt_Car_36,
         s_preInt_Car_23, s_preInt_Car_18, s_preInt_Self_19, s_preInt_Self_22, s_preInt_Self_27, 
         s_preInt_Self_31, s_preInt_Self_35, s_preInt_Des_33, s_preInt_Des_21, s_preInt_Des_17, s_preInt_Des_29, 
         s_preInt_Des_15, s_preInt_Car_28, s_preInt_Car_18, s_preInt_Des_24, s_preInt_Car_32, s_preInt_Car_23, 
         s_preInt_Des_26)
```


# EFA of the science interest items (pre science fair exposure)
```{r, efa.1, messages=FALSE, warning=FALSE, tidy=TRUE}
# Unidimensional EFA model ----
efa.1 <- fa(items, 1, fm="ml")
efa.1
x <- c(2, 3, 4, 5)
efa.2.6.oblimin <- lapply(2:6, function(x) {fa(items, nfactors=x, fm="ml", rotate = "oblimin")})
efa.2 <- efa.2.6.oblimin[[1]]
efa.2
efa.3 <- efa.2.6.oblimin[[2]]
efa.3
efa.4 <- efa.2.6.oblimin[[3]]
efa.4
efa.5 <- efa.2.6.oblimin[[4]]
efa.5

efa.3.4.5.bifac <- lapply(2:4, function(x) {omega(items, nfactors=x, sl=TRUE)})
efa.3.4.5.bifac
efa.3.bifac <- efa.3.4.5.bifac[[1]]
efa.4.bifac <- efa.3.4.5.bifac[[2]]
efa.5.bifac <- efa.3.4.5.bifac[[3]]


efa.4.5.secondOrder <- lapply(2:4, function(x) {omega(items, nfactors=x, sl=FALSE)})
efa.4.secondOrder <- efa.4.5.secondOrder[[1]]
efa.4.secondOrder
efa.5.secondOrder <- efa.4.5.secondOrder[[2]]
efa.5.secondOrder

# revised models
efa.3.rev.biFac <- lapply(3, function(x) {omega(rev.items.bifactor, nfactors=x, sl=TRUE)})
efa.3.rev.biFac

efa.3.secondOrder <- lapply(3, function(x) {omega(rev.items.secondOrder, nfactors=x, sl=FALSE)})
efa.3.rev.biFac
```
